# Generated by Django 5.0.1 on 2025-01-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='user',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='availability',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
