# Generated by Django 5.0.1 on 2025-01-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_volunteer_user_volunteer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(default='Enter your Name', max_length=100),
        ),
    ]
