# Generated by Django 5.0.1 on 2025-01-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_helprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=255)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('contact_details', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
