# Generated by Django 5.0.1 on 2025-01-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_volunteerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='location',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
