# Generated by Django 5.0.1 on 2025-01-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_volunteerapplication_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
