# Generated by Django 5.0.1 on 2025-01-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_role_profile_role_volunteer_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
