# Generated by Django 5.0.1 on 2025-01-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_volunteer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='contact_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
