# Generated by Django 5.0.1 on 2025-01-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_volunteer_contact_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='contact_details',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phone',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
