# Generated by Django 5.0.1 on 2025-01-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_volunteer_contact_details_volunteer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='phone',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='contact_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
