# Generated by Django 5.0.1 on 2025-01-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_volunteer_phone_volunteer_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='contact_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
