# Generated by Django 5.0.1 on 2025-01-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_volunteerapplication_contact_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='contact_details',
        ),
    ]
