# Generated by Django 5.0.1 on 2025-01-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_volunteer_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='contact_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
