# Generated by Django 5.0.1 on 2025-01-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_volunteer_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
