# Generated by Django 5.0.1 on 2025-01-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_volunteer_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('food', 'Food'), ('blood', 'Blood'), ('other', 'Other Resources')], max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O-'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('blood_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('food_type', models.CharField(blank=True, max_length=50, null=True)),
                ('food_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('supply_date', models.DateField(blank=True, null=True)),
                ('resource_description', models.TextField(blank=True, null=True)),
                ('resource_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
