# Generated by Django 5.0.1 on 2025-01-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_donation_alter_helprequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='money_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('food', 'Food'), ('blood', 'Blood'), ('other', 'Other Resources'), ('money', 'Money')], max_length=10),
        ),
    ]
