# Generated by Django 5.0.1 on 2025-01-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_blooddonation_fooddonation_moneydonation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='contact_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
