# Generated by Django 5.0.1 on 2025-01-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_blooddonation_contact_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonation',
            name='contact_details',
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='contact_phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
