# Generated by Django 5.0.1 on 2025-01-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_blooddonation_contact_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='contact_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='otherdonation',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='otherdonation',
            name='contact_phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
