# Generated by Django 5.0.1 on 2025-01-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_fooddonation_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='contact_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
