# Generated by Django 5.0.1 on 2025-01-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_fooddonation_contact_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonation',
            name='contact_address',
            field=models.CharField(max_length=200),
        ),
    ]
