# Generated by Django 5.0.1 on 2025-01-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_fooddonation_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdonation',
            name='contact_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='otherdonation',
            name='supply_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='contact_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
