# Generated by Django 5.0.1 on 2025-01-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_disasterreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisasterReport',
        ),
    ]
