# Generated by Django 5.0.1 on 2025-01-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_disasterreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disasterreport',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='disasterreport',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
