# Generated by Django 5.0.1 on 2025-02-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_task_help_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
