# Generated by Django 5.0.1 on 2025-02-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_volunteerapplication_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='profile_picture',
        ),
    ]
