# Generated by Django 5.0.1 on 2025-02-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_volunteer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
