# Generated by Django 5.0.1 on 2025-02-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_campaign_volunteers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='core.volunteer'),
        ),
    ]
