# Generated by Django 5.0.1 on 2025-02-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_volunteerapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='user',
        ),
    ]
