# Generated by Django 5.0.1 on 2025-02-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_volunteer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('Blood', 'Blood Donation'), ('Money', 'Money Donation'), ('Other', 'Other Donation'), ('Food', 'Food Donation')], max_length=50)),
                ('donation_id', models.PositiveIntegerField()),
                ('used_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usage_description', models.TextField()),
                ('usage_date', models.DateField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
    ]
