# Generated by Django 5.0.1 on 2025-02-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_resourceusage_alter_volunteer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='used_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherdonation',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherdonation',
            name='used_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
