# Generated by Django 5.0.1 on 2025-02-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_fooddonation_used_fooddonation_used_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddonation',
            name='used',
        ),
        migrations.RemoveField(
            model_name='fooddonation',
            name='used_date',
        ),
        migrations.RemoveField(
            model_name='otherdonation',
            name='used',
        ),
        migrations.RemoveField(
            model_name='otherdonation',
            name='used_date',
        ),
    ]
