# Generated by Django 5.0.1 on 2025-02-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_fooddonation_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('place_used', models.CharField(max_length=300)),
                ('time_used', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
