# Generated by Django 5.1.6 on 2025-03-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='certified_volunteers', to='core.certification'),
        ),
    ]
