# Generated by Django 5.1.6 on 2025-03-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_volunteer_certifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='certifications',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
