# Generated by Django 5.1.6 on 2025-03-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_volunteer_certifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='certificate',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='certificate_image',
            field=models.ImageField(blank=True, default='certificates/default_certificate.png', null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
    ]
