# Generated by Django 5.1.6 on 2025-03-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_volunteer_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='certificate_image',
            field=models.ImageField(blank=True, default='certificates/Screenshot 2025-03-05 122615.png', null=True, upload_to='certificates/'),
        ),
    ]
