# Generated by Django 5.1.6 on 2025-03-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_volunteer_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='certificate_image',
            field=models.ImageField(blank=True, default='media/Screenshot 2025-03-05 122615.png', null=True, upload_to='media/'),
        ),
    ]
