# Generated by Django 5.1.6 on 2025-03-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_volunteer_certificate_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='is_certified',
        ),
    ]
