# Generated by Django 5.1.6 on 2025-03-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_remove_volunteer_certificate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='certified',
            field=models.BooleanField(default=False),
        ),
    ]
