# Generated by Django 5.1.7 on 2025-04-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_volunteer_certificate_volunteer_certified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Awaiting Approval', 'Awaiting Approval'), ('Completed', 'Completed'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
