# Generated by Django 5.1.7 on 2025-04-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_helprequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
