# Generated by Django 5.1.7 on 2025-04-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_volunteerapplication_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disasterreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
